name: CI/CD

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master

            - name: install rsync
              run: sudo apt-get install rsync

            - name: copy via ssh
              run: - rsync -rvzD -e "ssh -o StrictHostKeyChecking=no" --exclude='.git/' --exclude='.github' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/app
            
            - name: run app
              run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -t -t -o StrictHostKeyChecking=no "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && cd ~/app && npm install l --omit=dev && pm2 start index.js && exit"